AnimalBundle\Entity\Mascotes:
    type: entity
    table: null
    repositoryClass: AnimalBundle\Repository\MascotesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
