<?php

namespace AnimalBundle\Repository;

/**
 * MascotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MascotesRepository extends \Doctrine\ORM\EntityRepository
{
}
