<?php

namespace AnimalBundle\Repository;

/**
 * PugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PugRepository extends \Doctrine\ORM\EntityRepository
{
    public function totsAll() {
        $em = $this->getEntityManager();
        $dql = "SELECT c.id, c.nom FROM AnimalBundle:Pug c";
        $query = $em->createQuery($dql);
        
        $pugs = $query->getResult();
        
        return $pugs;
    }    
}
